openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: "string"
            enum:
              - "sent"
              - "read"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        uuid: 
                          type: "string"
                        text:
                          type: "string"
                        status:
                          type: "string"
                          enum:
                            - "sent"
                            - "read"
              example:
                SuccessResponse:
                  value:
                    messages:
                      - uuid: "123e4567-e89b-12d3-a456-426614174000"
                        text: "Hello, World!"
                        status: "read"
                      - uuid: "123e4567-e89b-12d3-a456-426614174000"
                        text: "How are you today?"
                        status: "sent"
                      - uuid: "123e4567-e89b-12d3-a456-426614174000"
                        text: "Thanks, I'm fine. How about you?"
                        status: "sent"
  /messages/send:
    post:
      summary: Send a TextMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  maxLength: 255
                  example: "Hello, this is a test message!"
              required:
                - text
      responses:
        "201":
          description: Successfully sent the message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully sent"
        "400":
          description: Invalid request (e.g., missing text).
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Text is required"
              examples:
                MissingText:
                  value:
                    error: "Text is required"
